show databases;
create database aula4;
use aula4;
show tables;
desc cliente;
alter table new_table rename to Cliente;
desc contato;
insert into cliente(Nome,Data_Nascimento,Endereço) values ('André','02/03/1978','rua_A');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('Leandro','02/12/1974','rua_B');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('José','05/02/1980','rua_R');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('Marcelo','22/05/1970','rua_W');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('Camila','22/08/1975','rua_Z');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('Marcela','10/11/1981','rua_PP');
insert into cliente(Nome,Data_Nascimento,Endereço) values ('Andressa','22/08/1970','rua_T');
insert into contato(Telefone,Email,id_Cliente) values ('2733-4456','andre@gmail.com','1');
select *from cliente;
select *from contato;
insert into contato(Telefone,Email,id_Cliente) values ('2733-44221','leandro@gmail.com','2');
insert into contato(Telefone,Email,id_Cliente) values ('2733-4434','jose@gmail.com','3');
insert into contato(Telefone,Email,id_Cliente) values ('2733-4444','marcelo@gmail.com','4');
insert into contato(Telefone,Email,id_Cliente) values ('2733-4334','camila@gmail.com','5');
insert into contato(Telefone,Email,id_Cliente) values ('2733-4344','marcela@gmail.com','6');
insert into contato(Telefone,Email,id_Cliente) values ('2733-7844','andressa@gmail.com','7');
select *from pedido;
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('1','1','102','30/06/2020','5');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('2','1','125','29/06/2020','4');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('3','2','125','29/06/2020','4');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('4','3','456','28/06/2020','3');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('5','4','550','29/06/2020','4');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('6','4','1100','29/06/2020','4');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('7','6','550','30/06/2020','5');
insert into pedido(idPedido,id_Cliente,valor,data,prazo_entrega) values ('8','7','330','29/06/2020','4');
select *from pedido;
select pedido.*,cliente.* from pedido,cliente where pedido.id_Cliente=cliente.id_Cliente;
select cliente.*,pedido.* from cliente,pedido where cliente.id_Cliente=pedido.id_Cliente;
select cliente.nome,pedido.idpedido,pedido.valor from cliente,pedido where cliente.id_Cliente=pedido.id_Cliente;
select p.*,c.* from pedido p, cliente c where p.id_Cliente=c.id_Cliente;
select p.idpedido,c.nome,p.valor,p.prazo_entrega from cliente c inner join pedido p on p.id_Cliente=c.id_Cliente;